# Generated by Django 3.1.5 on 2021-01-05 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.RemoveField(
            model_name='category',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='modified',
        ),
        migrations.CreateModel(
            name='savecategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('isactive', models.IntegerField(blank=True, null=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_ids', to='sampleapp.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_id', to='sampleapp.subcategory')),
            ],
            options={
                'db_table': 'table_savecategory',
            },
        ),
    ]
